services:
  frontend:
    build: ./frontend
    container_name: Fusionpact_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name : Fusionpact_backend
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/app/app/data

  prometheus:
    container_name : Fusionpact_prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name : Fusionpact_grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123

volumes:
  backend-data:
  grafana-data: