    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # First, update the IP in GitHub secrets (if needed)
          CURRENT_IP=$(curl -s http://checkip.amazonaws.com)
          echo "Current IP: $CURRENT_IP"
          
          # Your deployment commands...
          cd /home/ubuntu/fusionpact-devops-challenge
          git pull origin main
          sudo docker-compose -f docker-compose.prod.yml down
          sudo docker-compose -f docker-compose.prod.yml up -d --build